### ISSUE TITLE
(Master Issue) Test which components work or don't work

### ISSUE THREAD

**Issue by maxgerhardt** [CommunityGD32Cores/GD32Core-New#8]
This is a master issue regarding the testing of all the components that were already in the core. It should be noted what features were tested, which worked, which did not work, and which features were not present. If a feature is marked with tickmark, it means it was working, otherwise it is untested, or tested to be non-working if there is a comment below it.

* [ ] GPIO
  * [X] Output working
  * [X] Input working
  * [X] Input with pullup working
  * [ ] Input with pulldownworking
* [ ] ADC / Analog in
  * [X] basic `analogRead()` on a channel
  * [X] `analogReadResolution()` works
  * [ ] all ADC channels work
  * [ ] read V_REF (analog voltage reference)
  * [ ] read V_TEMP (internal temperature sensor)
* [ ] Serial
   * [X] Baud rate setting
   * [X] Basic `println()` with all data types
   * [ ] Parity (Even / Odd / None)
   * [ ] Data bits (7 / 8 / 9)
   * [ ] Flow control
   * [ ] RS485 mode 
* [ ] I2C / Wire library
  * [X] Basic I2C transfers as master
  * [ ] `Wire.setClock()` function implemented (88d1cd79e196e13deaa67faeb7aea008f10157fd) but not measured / verified to be correct  (100kHz, 400kHz,..)
  * [ ] different I2C address sizes (7/8/10 bits?)
  * [ ] I2C slave
  * [ ] Bug #3 
* [ ] PWM
   * [X] working on some pins correctly
   * [ ] Bug #4 
* [ ] Timers
  * [ ] `HardwareTimer` works
* [ ] `tone()` / `noTone()`
* [ ] SPI
 * [ ] basic SPI transfers
 * [ ] all SPI modes work
 * [ ] all supporte clock settings work
 * [ ] SPI slave
 * [ ] Hardware NSS
* [ ] DAC
 * [ ] setting output voltage works
